export const TIERS = [
  {
    id: "tier-ex",
    name: "Explorer",
    price: "$1,500",
    price_cents: 150000,
    clearance: "Level 1",
    description: "Entry-level intelligence and ecosystem access for mission observers.",
    features: [
      "Weekly mission intelligence briefings",
      "Digital VIP credentials & member badge",
      "Basic profit distribution participation (0.5% base)",
      "Invitation to public SpaceX launch viewings",
    ],
    variant: "explorer",
  },
  {
    id: "tier-pi",
    name: "Pioneer",
    price: "$4,000",
    price_cents: 400000,
    clearance: "Level 2",
    description: "Advanced operational access with guaranteed presence at major hardware reveals.",
    features: [
      "Guaranteed VIP Passes to Tesla AI Day & Robotaxi events",
      "3× Enhanced monthly profit dividends (1.5% base)",
      "Priority seating at Starbase launch events",
      "Access to Private Member Discord for Alpha news",
    ],
    variant: "pioneer",
  },
  {
    id: "tier-va",
    name: "Vanguard",
    price: "$6,000",
    price_cents: 600000,
    clearance: "Full Operational Clearance",
    description: "The inner circle. Direct engagement with leadership and maximum ecosystem yields.",
    features: [
      "Private 1-on-1 Strategy Meeting with Elon Musk",
      "Maximum monthly profit dividend tier (3.5% target)",
      "Vanguard Council mission voting rights",
      "Lifetime VIP access to Starbase Launch Control",
      "Limited Edition Titanium Physical Membership Card",
    ],
    variant: "vanguard",
  },
] as const;
